# -*- coding: utf-8 -*-
from pathlib import Path
from html import escape
import json
import hashlib
ROOT=Path(__file__).resolve().parents[1]
BASE='https://kanghyunmin-bot.github.io'
GH='https://github.com/kanghyunmin-bot/'
def asset(path):
 return path+'?v='+hashlib.sha256((ROOT/path).read_bytes()).hexdigest()[:10]

apps=[dict(id='topdf',name='TopDF',icon='topdf.png',category='DOCUMENTS',platform='macOS · Windows · Android',version='1.0.0-rc.2 · 사전 릴리스',headline='파일을 PDF로.<br>내 기기 안에서.',description='Word, Excel, PowerPoint, HWP/HWPX 문서를 오프라인에서 PDF로 변환하세요. 페이지 범위와 용지 방향을 고르고, 원하는 위치에 저장합니다.',repo='topdf',tag='v1.0.0-rc.2',features=['외부 변환 API와 계정 없이 사용','Mac·Windows 우클릭 메뉴와 Android 공유 메뉴','페이지 선택, 미리보기, PDF 저장과 인쇄'],steps=['운영체제에 맞는 릴리스 파일을 다운로드합니다.','Mac·Windows 앱을 실행해 우클릭 메뉴를 등록하거나 Android 공유 메뉴에서 엽니다.','페이지와 방향을 고른 뒤 PDF를 저장합니다.'],notice='사전 릴리스입니다. Mac 서명·공증과 Windows 배포자 서명, 독립 실기기 설치·인쇄 검증은 남아 있습니다. 복잡한 서식과 글꼴은 원본과 차이가 날 수 있습니다.'),dict(id='mtog',name='MtoG',icon='mtog.png',category='CONNECTED DEVICES',platform='macOS 14+ · Android 12+',version='0.2.0 · 시험 릴리스',headline='Galaxy Tab을<br>Mac의 두 번째 화면으로.',description='USB로 연결한 Galaxy Tab을 터치 가능한 확장 화면으로 활용하고, 텍스트·사진·파일을 Mac과 양방향으로 공유합니다.',repo='MactoGalaxy',tag='v0.2.0',features=['Apple Silicon·Intel 유니버설 Mac 앱','태블릿 터치로 Mac 앱 조작','텍스트 동기화와 사진·파일 공유'],steps=['Mac DMG와 Android APK를 설치하고 Mac에 ADB를 준비합니다.','USB 디버깅을 허용하고 페어링 코드를 등록합니다.','화면 기록·손쉬운 사용 권한을 허용한 뒤 확장 화면을 시작합니다.'],notice='시험 릴리스이며 Mac 공증 전입니다. 가상 디스플레이는 macOS 비공개 API를 사용합니다. 실제 프레임률은 기기와 부하에 따라 달라집니다.'),dict(id='zoom',name='WinCtrlZoom',icon='zoom.png',category='DESKTOP TOOLS',platform='Windows 10 · 11',version='0.2.0',headline='보고 싶은 곳을<br>부드럽게 확대.',description='Win + Ctrl을 누르고 마우스 휠을 돌리세요. 마우스 위치를 중심으로 화면을 확대하고, 가장자리에서 마우스를 움직여 화면을 이동합니다.',repo='WinCtrlZoom',tag='v0.2.0',features=['100%부터 400%까지 부드러운 확대','트레이에서 감도와 자동 실행 설정','관리자 권한과 네트워크 연결 없이 사용'],steps=['설치판 EXE 또는 포터블 ZIP을 다운로드합니다.','앱을 실행하고 Win + Ctrl + 마우스 휠로 확대합니다.','Win + Ctrl + 0으로 원래 크기로 돌아갑니다.'],notice='코드서명 전 버전이므로 SmartScreen 경고가 표시될 수 있습니다. 디스플레이별 서로 다른 확대율과 터치·펜 좌표 보정은 지원하지 않습니다. Ubuntu GNOME 포트는 실험 단계입니다.')]
(ROOT/'content.json').write_text(json.dumps({'updated':'2026-10-02','apps':apps},ensure_ascii=False,indent=2)+'\n')
def shell(title,description,body,page='home'):
 extra_head = f'<link rel="stylesheet" href="{asset("assets/immersive.css")}">' if page=='home' else ''
 extra_scripts = ''.join(f'<script src="{asset(path)}" defer></script>' for path in ['assets/vendor/gsap.min.js','assets/vendor/ScrollTrigger.min.js','assets/vendor/lenis.min.js'])+f'<script type="module" src="{asset("assets/robot-world.js")}"></script>' if page=='home' else ''
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if page==key else '')+f'>{label}</a>' for key,url,label in [('home','index.html','홈'),('robotics','robotics.html','로봇 연구'),('apps','apps.html','만든 도구')])
 return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — HYUNMIN LAB</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#f1f6ff"><meta property="og:title" content="{title} — HYUNMIN LAB"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><meta property="og:image" content="{BASE}/{asset('assets/social.png')}"><meta property="og:url" content="{BASE}/{page if page!='home' else 'index'}.html"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{asset('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="{asset('assets/style.css')}"><link rel="canonical" href="{BASE}/{page if page!='home' else 'index'}.html">{extra_head}</head><body class="{'immersive' if page=='home' else ''}"><a class="skip" href="#main">본문 바로가기</a><header><a class="brand" href="index.html"><span class="brand-mark"><img src="{asset('assets/identity-mark.svg')}" alt="" width="28" height="28"></span> HYUNMIN <b>LAB</b></a><nav aria-label="주 메뉴">{nav}<a class="github" href="{GH.rstrip('/')}">GitHub ↗</a></nav></header><div class="glass-controls" data-liquid-ignore><button class="glass-toggle" type="button" aria-pressed="false">유리 효과</button></div><main id="main">{body}</main><footer><a class="brand" href="index.html">HYUNMIN LAB</a><p>로봇을 중심으로, 연결하고 실험합니다.<br>강현민 · ROBOTICS / SIDE PROJECTS</p><div><a href="{GH.rstrip('/')}">GitHub ↗</a><a href="{GH}kanghyunmin-bot.github.io/issues">사이트 문의 ↗</a><span>© 2026 Hyunmin Kang · 업데이트 2026.10.02</span></div></footer><script src="{asset('assets/vendor/liquidGL.js')}" defer></script><script src="{asset('assets/site.js')}" defer></script>{extra_scripts}</body></html>'''
home=(ROOT/'templates/home.html').read_text()
for path in ['assets/topdf.png','assets/mtog.png','assets/zoom.png','assets/robot-poster.svg']:
 home=home.replace('src="'+path+'"','src="'+asset(path)+'"')
(ROOT/'index.html').write_text(shell('로봇을 중심으로, 연결하고 실험합니다','강현민의 로봇과 VLA 연구. 지상·수중·공중의 인식·학습·제어를 연결하고 실험하려 합니다. 공개 연구와 부가 앱을 소개합니다.',home))
sections=[]
for i,a in enumerate(apps,1):
 sections.append(f'''<article class="app-detail" id="{a['id']}"><div class="detail-title"><span class="micro">0{i} / {a['category']}</span><img src="{asset('assets/'+a['icon'])}" width="96" height="96" alt="{a['name']} 아이콘"><h2>{a['name']}</h2><span class="version">{a['version']}</span><div class="platform">{a['platform']}</div></div><div class="detail-body"><h3>{a['headline']}</h3><p class="lead">{a['description']}</p><ul class="feature-list">{''.join('<li>'+x+'</li>' for x in a['features'])}</ul><div class="actions"><a class="button primary" href="{GH}{a['repo']}/releases/tag/{a['tag']}">다운로드 ↗</a><a class="button outline" href="{GH}{a['repo']}">소스 · 사용 안내 ↗</a></div><details><summary>시작하는 방법</summary><ol>{''.join('<li>'+x+'</li>' for x in a['steps'])}</ol></details><p class="notice"><strong>사용 전 확인</strong> {a['notice']}</p><a class="text-link" href="{GH}{a['repo']}/issues">문의 · 버그 제보 ↗</a></div></article>''')
body='<section class="page-intro"><div class="eyebrow">SIDE PROJECTS / THE TOOL COLLECTION</div><h1>필요할 때 만든 도구들.</h1><p class="lead">로봇 연구가 중심이지만, 일상의 불편도 직접 풀어봅니다.<br>문서 변환, 기기 연결, 화면 확대를 위해 만든 부가 프로젝트입니다.</p><div class="jump-links">'+''.join(f'<a href="#{a["id"]}">{a["name"]} ↓</a>' for a in apps)+'</div></section>'+''.join(sections)
(ROOT/'apps.html').write_text(shell('앱','TopDF 오프라인 PDF 변환, MtoG Galaxy Tab 확장 화면, WinCtrlZoom Windows 화면 확대. 다운로드와 사용 안내.',body,'apps'))
robot=f'''<section class="page-intro"><div class="eyebrow">ROBOTICS / RESEARCH NOTES</div><h1>로봇이 세상을 이해하고,<br><span>스스로 움직이도록.</span></h1><p class="lead">지상·수중·공중 로봇에 VLA를 연결하는 방향을 탐색합니다.<br>현재 공개한 연구는 수중 시뮬레이션과 시각 추적 중심입니다.</p><div class="tags"><span>ROS 2</span><span>MuJoCo</span><span>ArduSub</span><span>VLA</span><span>Visual Odometry</span></div></section><section class="robot-feature" id="simulation"><div class="robot-image"><img src="https://raw.githubusercontent.com/kanghyunmin-bot/ROS2-mujoco-UUVsimulator/main/docs/assets/research-pool-20260912.png" alt="MuJoCo로 렌더링한 수중 ROV 연구 수영장" loading="lazy"><span>MUJOCO SIMULATION · 실물 사진이 아닌 시뮬레이터 렌더</span></div><div class="robot-copy"><div class="eyebrow">01 / UNDERWATER SIMULATION</div><h2>수중 ROV<br>연구 시뮬레이터</h2><p>MuJoCo 물리 환경에 ArduSub SITL과 ROS 2를 연결합니다. 전방·손 카메라와 센서, 부표·자석·줄 접촉을 구성하고 시연 수집과 로봇 학습 흐름을 실험합니다.</p><div class="tags"><span>Ubuntu 22.04</span><span>ROS 2 Humble</span><span>연구 개발 중</span></div><a class="button primary" href="{GH}ROS2-mujoco-UUVsimulator">프로젝트 · 실행 안내 ↗</a></div></section><section class="research-columns"><article><div class="eyebrow">02 / ROBOT LEARNING</div><h2>시연에서 배우고,<br>행동을 보정하기.</h2><p>수중 시뮬레이터의 시연을 VLA 학습 입력으로 연결하고, 동결한 정책에 잔차 PPO를 더하는 연구 흐름을 구현합니다.</p><div class="pipeline"><span>영상 · 언어 · 상태</span><b>↓</b><span>VLA 기본 행동</span><b>↓</b><span>잔차 정책 · 제어</span></div><p class="notice">공개 저장소에는 학습 가중치와 원본 데이터가 포함되지 않습니다. 실로봇 전이와 정밀 작업 일반화는 미검증입니다.</p><a class="text-link" href="{GH}ROS2-mujoco-UUVsimulator/tree/main/tools/vla_gui">VLA 구현 문서 ↗</a></article><article><div class="eyebrow">03 / PERCEPTION</div><h2>물속 영상에서<br>움직임을 추적하기.</h2><p>영상 특징 검출, KLT 추적, 기하 검증을 분리한 시각 프런트엔드입니다. 파라미터 비교와 추적 결과 기록, RViz 경로 표시를 위한 도구를 제공합니다.</p><div class="pipeline"><span>영상 · 특징 검출</span><b>↓</b><span>KLT · 기하 검증</span><b>↓</b><span>추적 로그 · 경로 시각화</span></div><p class="notice">MP4 단독 경로는 임의 스케일의 시각 오도메트리입니다. 완성된 VIO-SLAM이나 실제 거리 정확도를 입증한 결과로 소개하지 않습니다.</p><a class="text-link" href="{GH}UUV-VINS-SLAM">프로젝트 · 기술 문서 ↗</a></article></section><section class="research-principle"><div class="eyebrow">HOW I DOCUMENT</div><h2>결과만큼, 검증 범위도 중요합니다.</h2><p>시뮬레이션 실행, 소프트웨어 검사, 실기기 검증을 구분해 기록합니다.<br>최신 구현과 실행 조건은 각 프로젝트의 README 및 검증 문서를 기준으로 확인하세요.</p><a class="text-link" href="{GH}ROS2-mujoco-UUVsimulator/tree/main/docs/versions">시뮬레이터 검증 기록 ↗</a></section>'''
robot += '<section class="research-principle" id="directions"><div class="eyebrow">NEXT DIRECTIONS / VLA</div><h2>지상에서 시작해, 수중과 공중으로.</h2><p>지상 로봇의 인식·언어·행동 연결을 먼저 실험하고, 수중과 공중 로봇으로 확장하는 것을 지향합니다. 이는 앞으로의 연구 방향이며, 모든 환경에서 VLA를 구현하거나 검증했다는 뜻은 아닙니다.</p><div class="tags"><span>지상 VLA · 계획</span><span>수중 · 공개 연구 구현</span><span>공중 VLA · 탐색 방향</span></div></section>'
(ROOT/'robotics.html').write_text(shell('로봇 연구','수중 ROV 시뮬레이터, ROS 2·MuJoCo·ArduSub 통합, VLA 로봇 학습과 영상 특징 추적 프로젝트.',robot,'robotics'))
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}/{p}</loc><lastmod>2026-10-02</lastmod></url>' for p in ['index.html','apps.html','robotics.html'])+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'/sitemap.xml\n')
(ROOT/'404.html').write_text(shell('페이지를 찾을 수 없습니다','HYUNMIN LAB 홈으로 돌아가세요.','<section class="page-intro"><div class="eyebrow">404</div><h1>여기는 아직 빈 페이지예요.</h1><a class="button primary" href="/">홈으로 돌아가기 →</a></section>','404'))
